### PR TITLE
Add systemd service script

### PR DESCRIPTION
**Pull request by begizi**
used for creating a self restarting service for linux systems

### CODE REVIEW

**Comment by samccone** [comment]
should this be part of the repo :truck:

**Comment by begizi** [comment]
I added it to `contrib` where I feel like we could put useful scripts and configurations for anyone else wanting to run it on a pi or otherwise.

**Comment by begizi** [comment]
Nevertheless, I think using systemd is the right way to go for running our server on our pi

**Comment by samccone** [comment]
prob, lgtm test on the device and :ship:

**Comment by begizi** [comment]
TODO:

  * [ ] Move to better named directory. ie `scripts` or `deploy-scripts`
  * [ ] Change description to better reflect the project
  * [ ] Test on Raspberry pi

**Comment by begizi** [comment]
Closing for now. The pi doesn't use systemd by default. Building a runit script instead.

**Pull request closed without merging**
